swagger: '2.0'
info:
  title: XSS Form Test
  description: |
    <form id="fakeForm" onsubmit="event.preventDefault(); alert('Captured input: ' + document.getElementById('userInput').value);">
      <label for="userInput">Enter Information:</label><br>
      <input type="text" id="userInput" placeholder="Enter text"><br>
      <button type="submit">Submit</button>
    </form>
  version: "1.0.0"
paths: {}
